"""Generate the TypeScript API contract from the canonical Pydantic models."""

from __future__ import annotations

import argparse
import types
from datetime import date, datetime
from enum import Enum
from pathlib import Path
from typing import Literal, Union, get_args, get_origin

from app.models import (
    Analysis,
    AnalysisStatus,
    AnalysisSummary,
    Coverage,
    FactorKey,
    ScoreFactor,
    SourceStat,
    Stage,
    TimelinePoint,
    Trend,
    UseCase,
)
from pydantic import BaseModel

from nextwave.contracts import (
    CandidateAssessment,
    CandidateFeatures,
    CandidateStatus,
    DevelopmentStage,
    Evidence,
    ExclusionReason,
    ModelPrediction,
    SourceType,
    TrustLevel,
)

TARGET = Path(__file__).resolve().parent.parent / "frontend/src/lib/contracts.generated.ts"

ENUMS = (
    SourceType,
    TrustLevel,
    DevelopmentStage,
    CandidateStatus,
    ExclusionReason,
)
ALIASES = (
    ("AnalysisStatus", AnalysisStatus),
    ("FactorKey", FactorKey),
)
MODELS = (
    Evidence,
    CandidateFeatures,
    ModelPrediction,
    CandidateAssessment,
    TimelinePoint,
    ScoreFactor,
    UseCase,
    Trend,
    SourceStat,
    Coverage,
    Stage,
    Analysis,
    AnalysisSummary,
)
MODEL_BASES = {Trend: CandidateAssessment}
FIELD_TYPE_OVERRIDES = {
    (ScoreFactor, "key"): "FactorKey",
    (Analysis, "status"): "AnalysisStatus",
    (AnalysisSummary, "status"): "AnalysisStatus",
}


def _typescript_type(annotation: object) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)

    if annotation in {str, date, datetime}:
        return "string"
    if annotation is int or annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is type(None):
        return "null"
    if origin is Literal:
        return " | ".join(repr(value) for value in args)
    if origin in {Union, types.UnionType}:
        return " | ".join(_typescript_type(value) for value in args)
    if origin in {list, tuple}:
        return f"{_typescript_type(args[0])}[]"
    if origin is dict:
        return f"Record<{_typescript_type(args[0])}, {_typescript_type(args[1])}>"
    if isinstance(annotation, type) and issubclass(annotation, (Enum, BaseModel)):
        return annotation.__name__
    raise TypeError(f"Unsupported contract annotation: {annotation!r}")


def _render_alias(name: str, annotation: object) -> str:
    return f"export type {name} = {_typescript_type(annotation)}"


def _render_enum(enum: type[Enum]) -> str:
    values = " | ".join(repr(member.value) for member in enum)
    single_line = f"export type {enum.__name__} = {values}"
    if len(single_line) <= 100:
        return single_line
    members = "\n".join(f"  | {member.value!r}" for member in enum)
    return f"export type {enum.__name__} =\n{members}"


def _render_model(model: type[BaseModel]) -> str:
    base = MODEL_BASES.get(model)
    inherited = set(base.model_fields) if base else set()
    extension = f" extends {base.__name__}" if base else ""
    lines = [f"export interface {model.__name__}{extension} {{"]
    for name, field in model.model_fields.items():
        if name in inherited:
            continue
        field_type = FIELD_TYPE_OVERRIDES.get((model, name), _typescript_type(field.annotation))
        lines.append(f"  {name}: {field_type}")
    lines.append("}")
    return "\n".join(lines)


def render_typescript_contracts() -> str:
    sections = [
        (
            "// Generated from the Pydantic models in backend/app/models.py and\n"
            "// src/nextwave/contracts.py. Do not edit this file by hand."
        ),
        *(_render_enum(enum) for enum in ENUMS),
        *(_render_alias(name, annotation) for name, annotation in ALIASES),
        *(_render_model(model) for model in MODELS),
    ]
    return "\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_typescript_contracts()

    if args.write:
        TARGET.write_text(rendered, encoding="utf-8")
        return 0
    if args.check:
        if TARGET.read_text(encoding="utf-8") != rendered:
            parser.error(f"{TARGET} is stale; run this command with --write")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
