"""Query scope resolution and bounded discovery planning."""

from .contracts import (
    ANALYSIS_SCOPE_SCHEMA_VERSION,
    DISCOVERY_BUDGET_SCHEMA_VERSION,
    DISCOVERY_PLAN_SCHEMA_VERSION,
    QUERY_INTERPRETATION_SCHEMA_VERSION,
    QUERY_RESOLUTION_SCHEMA_VERSION,
    AnalysisScope,
    DiscoveryBudget,
    DiscoveryPlan,
    QueryInterpretation,
    QueryResolution,
    ScopeGranularity,
    TaxonomyCandidate,
    TaxonomyLevel,
    TaxonomyLookupStatus,
)
from .planner import (
    DEFAULT_DISCOVERY_BUDGETS,
    DEFAULT_RESOLVER_VERSION,
    build_analysis_scope,
    build_discovery_plan,
)
from .query_resolver import (
    MAX_TAXONOMY_CANDIDATES,
    OPENALEX_API_ROOT,
    QUERY_RESOLVER_VERSION,
    OpenAlexTaxonomySource,
    QueryInterpreter,
    QueryResolver,
    StructuredQueryInterpreter,
    TaxonomySource,
    build_interpretation_prompt,
    parse_openalex_taxonomy_response,
    select_taxonomy_candidate,
    taxonomy_match_score,
)

__all__ = [
    "ANALYSIS_SCOPE_SCHEMA_VERSION",
    "DEFAULT_DISCOVERY_BUDGETS",
    "DEFAULT_RESOLVER_VERSION",
    "DISCOVERY_BUDGET_SCHEMA_VERSION",
    "DISCOVERY_PLAN_SCHEMA_VERSION",
    "MAX_TAXONOMY_CANDIDATES",
    "OPENALEX_API_ROOT",
    "QUERY_INTERPRETATION_SCHEMA_VERSION",
    "QUERY_RESOLUTION_SCHEMA_VERSION",
    "QUERY_RESOLVER_VERSION",
    "AnalysisScope",
    "DiscoveryBudget",
    "DiscoveryPlan",
    "OpenAlexTaxonomySource",
    "QueryInterpretation",
    "QueryInterpreter",
    "QueryResolution",
    "QueryResolver",
    "ScopeGranularity",
    "StructuredQueryInterpreter",
    "TaxonomyCandidate",
    "TaxonomyLevel",
    "TaxonomyLookupStatus",
    "TaxonomySource",
    "build_analysis_scope",
    "build_discovery_plan",
    "build_interpretation_prompt",
    "parse_openalex_taxonomy_response",
    "select_taxonomy_candidate",
    "taxonomy_match_score",
]
