"""Source connector contracts and snapshot support."""

from .contracts import (
    CONNECTOR_REQUEST_SCHEMA_VERSION,
    SNAPSHOT_MANIFEST_SCHEMA_VERSION,
    SOURCE_QUERY_SCHEMA_VERSION,
    ConnectorError,
    ConnectorId,
    ConnectorRequest,
    ConnectorRun,
    ConnectorStatus,
    QueryParameter,
    QueryPurpose,
    RawResponseArtifact,
    RetrievalChannel,
    SnapshotManifest,
    SnapshotStatus,
    SourceQuery,
)
from .crossref import (
    CROSSREF_SELECT_FIELDS,
    CROSSREF_WORKS_ENDPOINT,
    CrossrefConnector,
    build_crossref_request,
    crossref_request_url,
)
from .crossref_parser import (
    CrossrefParseIssue,
    CrossrefParseResult,
    parse_crossref_response,
    parse_crossref_work,
)
from .gdelt import (
    GDELT_DOC_ENDPOINT,
    GdeltConnector,
    build_gdelt_request,
    build_gdelt_timeline_request,
    gdelt_request_url,
)
from .gdelt_parser import (
    GdeltParseIssue,
    GdeltParseResult,
    GdeltTimelinePoint,
    GdeltTimelineResult,
    canonicalize_article_url,
    parse_gdelt_article,
    parse_gdelt_response,
    parse_gdelt_timeline_response,
)
from .http import HttpResponse, HttpTransport, UrllibHttpTransport
from .identifiers import doi_url, normalize_doi
from .mediacloud import (
    MEDIACLOUD_COUNT_OVER_TIME_ENDPOINT,
    MEDIACLOUD_PLATFORM,
    MEDIACLOUD_STORY_LIST_ENDPOINT,
    MediaCloudConnector,
    build_mediacloud_story_request,
    build_mediacloud_timeline_request,
    mediacloud_request_url,
)
from .mediacloud_parser import (
    MediaCloudParseIssue,
    MediaCloudParseResult,
    MediaCloudTimelinePoint,
    MediaCloudTimelineResult,
    parse_mediacloud_response,
    parse_mediacloud_story,
    parse_mediacloud_timeline_response,
)
from .openalex import (
    OPENALEX_SELECT_FIELDS,
    OPENALEX_WORKS_ENDPOINT,
    OpenAlexConnector,
    build_openalex_request,
    openalex_request_url,
)
from .openalex_parser import (
    OpenAlexDiscoveryHints,
    OpenAlexHintIssue,
    OpenAlexKeywordHint,
    OpenAlexParseIssue,
    OpenAlexParseResult,
    OpenAlexTopicHint,
    parse_openalex_discovery_hints,
    parse_openalex_response,
    parse_openalex_work,
    reconstruct_openalex_abstract,
)
from .snapshots import SnapshotWriter

__all__ = [
    "CONNECTOR_REQUEST_SCHEMA_VERSION",
    "CROSSREF_SELECT_FIELDS",
    "CROSSREF_WORKS_ENDPOINT",
    "GDELT_DOC_ENDPOINT",
    "SNAPSHOT_MANIFEST_SCHEMA_VERSION",
    "SOURCE_QUERY_SCHEMA_VERSION",
    "ConnectorError",
    "ConnectorId",
    "ConnectorRequest",
    "ConnectorRun",
    "ConnectorStatus",
    "CrossrefConnector",
    "CrossrefParseIssue",
    "CrossrefParseResult",
    "GdeltConnector",
    "GdeltParseIssue",
    "GdeltParseResult",
    "GdeltTimelinePoint",
    "GdeltTimelineResult",
    "HttpResponse",
    "HttpTransport",
    "MEDIACLOUD_COUNT_OVER_TIME_ENDPOINT",
    "MEDIACLOUD_PLATFORM",
    "MEDIACLOUD_STORY_LIST_ENDPOINT",
    "MediaCloudConnector",
    "MediaCloudParseIssue",
    "MediaCloudParseResult",
    "MediaCloudTimelinePoint",
    "MediaCloudTimelineResult",
    "OPENALEX_SELECT_FIELDS",
    "OPENALEX_WORKS_ENDPOINT",
    "OpenAlexConnector",
    "OpenAlexDiscoveryHints",
    "OpenAlexHintIssue",
    "OpenAlexKeywordHint",
    "OpenAlexParseIssue",
    "OpenAlexParseResult",
    "OpenAlexTopicHint",
    "QueryParameter",
    "QueryPurpose",
    "RawResponseArtifact",
    "RetrievalChannel",
    "SnapshotManifest",
    "SnapshotStatus",
    "SnapshotWriter",
    "SourceQuery",
    "UrllibHttpTransport",
    "build_openalex_request",
    "build_crossref_request",
    "build_gdelt_request",
    "build_gdelt_timeline_request",
    "build_mediacloud_story_request",
    "build_mediacloud_timeline_request",
    "canonicalize_article_url",
    "crossref_request_url",
    "doi_url",
    "gdelt_request_url",
    "mediacloud_request_url",
    "normalize_doi",
    "openalex_request_url",
    "parse_openalex_response",
    "parse_openalex_discovery_hints",
    "parse_openalex_work",
    "parse_crossref_response",
    "parse_crossref_work",
    "parse_gdelt_article",
    "parse_gdelt_response",
    "parse_gdelt_timeline_response",
    "parse_mediacloud_response",
    "parse_mediacloud_story",
    "parse_mediacloud_timeline_response",
    "reconstruct_openalex_abstract",
]
