// Generated from the Pydantic models in backend/app/models.py and
// src/nextwave/contracts.py. Do not edit this file by hand.

export type SourceType =
  | 'scientific_publication'
  | 'patent'
  | 'standard'
  | 'regulator'
  | 'university'
  | 'company'
  | 'industry_media'
  | 'analytical_report'
  | 'conference'
  | 'social_or_blog'
  | 'other'

export type TrustLevel = 'high' | 'medium' | 'low' | 'unknown'

export type DevelopmentStage =
  | 'research'
  | 'prototype'
  | 'pilot'
  | 'early_adoption'
  | 'mass_adoption'
  | 'unknown'

export type CandidateStatus = 'main' | 'watchlist' | 'excluded'

export type ExclusionReason =
  | 'mature'
  | 'mass_adoption'
  | 'industry_standard'
  | 'marketing_hype'
  | 'insufficient_trust'
  | 'irrelevant'
  | 'duplicate'

export type AnalysisStatus = 'pending' | 'running' | 'done' | 'empty' | 'error'

export type FactorKey = 'growth' | 'novelty' | 'independence' | 'evidence'

export interface Evidence {
  evidence_id: string
  title: string
  url: string
  source_type: SourceType
  language: string
  trust_level: TrustLevel
  published_at: string | null
  retrieved_at: string | null
  excerpt: string | null
  generated_summary: boolean
}

export interface CandidateFeatures {
  stage: DevelopmentStage
  independent_source_count: number
  source_type_diversity: number
  independent_actor_count: number
  publication_momentum: number | null
  patent_momentum: number | null
  evidence_recency_days: number | null
  mass_adoption: boolean | null
  formed_market: boolean | null
  industry_standard: boolean | null
  promotional_source_share: number | null
}

export interface ModelPrediction {
  weak_signal_score: number
  model_version: string
  feature_version: string
  calibrated: boolean
}

export interface CandidateAssessment {
  candidate_id: string
  canonical_name: string
  query: string
  status: CandidateStatus
  features: CandidateFeatures
  prediction: ModelPrediction
  explanation: string
  evidence: Evidence[]
  exclusion_reason: ExclusionReason | null
  priority_score: number | null
}

export interface TimelinePoint {
  period: string
  documents: number
  share: number
}

export interface ScoreFactor {
  key: FactorKey
  value: number
  explanation: string
}

export interface UseCase {
  title: string
  organization: string | null
  description: string
  url: string
}

export interface Trend extends CandidateAssessment {
  rank: number
  summary: string
  factors: ScoreFactor[]
  problem: string
  advantage: string
  hypothesis: string | null
  use_case: UseCase
  first_seen: string
  timeline: TimelinePoint[]
  document_count: number
  limitations: string[]
}

export interface SourceStat {
  name: string
  source_type: SourceType
  documents: number
}

export interface Coverage {
  directions: string[]
  examples: string[]
  documents_from: string
  documents_to: string
  document_count: number
  sources: SourceStat[]
  corpus_version: string
  method_version: string
  updated_at: string
  thresholds: Record<string, number>
}

export interface Stage {
  key: string
  label: string
}

export interface Analysis {
  id: string
  query: string
  status: AnalysisStatus
  stage: string | null
  progress: number
  notice: string | null
  created_at: string
  finished_at: string | null
  corpus_version: string
  method_version: string
  trends: Trend[]
}

export interface AnalysisSummary {
  id: string
  query: string
  status: AnalysisStatus
  created_at: string
  trend_count: number
}
